spring:
    data:
      mongodb:
        host: ds137336.mlab.com
        port: 37336
        database: bombermanx
        username: bomberman
        password: bomberman
    redis:
      host: 10.0.0.4
      port: 6379
      #password:
